### ISSUE TITLE
r.get is not a function error after upgrading from v1.2.8 to v2.1.13

### ISSUE THREAD

**Issue by Vineetkhadloya** [grafana/grafana-polystat-panel#426]
I upgrade my Grafana from v8.5 to v9.3.0 and Polystat Plugin from v1.2.8 to v2.1.13. 
This breaks most of my dashboards which were working earlier and I keep getting the error r.get is not a function when trying to render the polystat. 

![Image](https://github.com/user-attachments/assets/9a9ee99b-de4f-4a5b-8b91-fb57dd0f6f01)
![Image](https://github.com/user-attachments/assets/aa71670c-5e93-42cb-a772-26bc553a5563)

I am okay with downgrading my Polystat Version.

**Comment by briangann** [comment]
will double check this, seems to be popping up on a variety of grafana versions.  likely a runtime compatibility issue

**Comment by Vineetkhadloya** [comment]
Thanks for the response @briangann !! Please let me know if you need more details when working on this.

**Comment by briangann** [comment]
due to api changes the minimum version of Grafana that will work is v9.5, there were breaking changes that causes this error in the runtime.
