### ISSUE TITLE
After upgrading at last version (2.1.11) all polystat panels show "l.add is not a function"

### ISSUE THREAD

**Issue by dequeee** [grafana/grafana-polystat-panel#389]
Hi,

I had previously opened an incident because with Grafana version 9.5.19 and the polystat panel at version 1.2.11, the tooltip was not shown.

As recommended I’m trying to update the plugin.

I’m trying to do this on a test server first, with Grafana version 9.2.10. I manually extracted from the zip file of version 2.1.11, downloaded in the plugin installation section, inside the correct directory, first renaming the old version of the plugin adding _old at the end.

Looking from the web interface the new version is detected correctly. When I try to create a new panel, or to look at a panel created with the previous version, it shows as error  "l. add is not a function", trying to click on the error brings me to the JSON section of the inspect. 

Is the problem that version 9.5.19 of Grafana supports version 2.1.11 of polystat while version 9.2.10 of Grafana does not support the updated version of polystat? Or is it something else?

Best Regards!

**Comment by dequeee** [comment]
I saw another issue open for a similar issue. I wanted to point out that in my case even panels with data that would be shown present that problem

**Comment by briangann** [comment]
we're looking into this, it does sound like a regression

**Comment by dequeee** [comment]
Hi,

Thanks for the answer.

In the meantime I would like to ask you if there was a version of the polystat panel working in Grafana version 9.5.19, that allows you to see the tooltip, unlike version polystat v1.2.11 and that does not present the bug specified in this issue. If there is a working version, would it be possible to find a way to download it manually? 

Best regards!

**Comment by briangann** [comment]
I'll have a fix for this shortly, the variety of bugs in older versions would likely cause even more problems.

The issue is due to removal of a runtime api function in v9.5+, and an edge case of using it which didn't have test coverage.
